import {
  Sparkles,
  Code,
  Rocket,
  Zap,
  Send,
  Download,
  Eye,
  Search,
  Play,
  Code2,
  BookOpen,
  Shield,
  Users,
  Menu,
  X,
  ChevronRight,
  ChevronDown,
  ExternalLink,
  Copy,
  Check,
  AlertCircle,
  Info,
  Loader2,
  Wallet,
  LogOut,
  Layout,
  Server,
  Settings,
  Link,
  File,
  FileText,
  Folder,
  Lightbulb,
} from "lucide-react"

export const Icons = {
  sparkles: Sparkles,
  code: Code,
  rocket: Rocket,
  zap: Zap,
  send: Send,
  download: Download,
  eye: Eye,
  search: Search,
  play: Play,
  code2: Code2,
  bookOpen: BookOpen,
  shield: Shield,
  users: Users,
  menu: Menu,
  x: X,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  externalLink: ExternalLink,
  copy: Copy,
  check: Check,
  alertCircle: AlertCircle,
  info: Info,
  loader: Loader2,
  layout: Layout,
  server: Server,
  settings: Settings,
  link: Link,
  file: File,
  fileText: FileText,
  folder: Folder,
  lightbulb: Lightbulb,
}

// Additional icon exports for wallet functionality
export const WalletIcon = Wallet
export const LogOutIcon = LogOut
export const LoaderIcon = Loader2

export {
  Sparkles as SparklesIcon,
  Download as DownloadIcon,
  Eye as EyeIcon,
  Search as SearchIcon,
}